# Default values for nats.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: nats
  tag: 0.7.2
  pullPolicy: IfNotPresent
service:
  #namespace: nats
  #name: test-nats
  #type: ClusterIP
  externalPort: 4222
  internalPort: 4222
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi

