apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    component: {{ template "name" . }}
spec:
  selector:
    component: {{ template "name" . }}
  clusterIP: None
  ports:
  - port: 4222
    protocol: TCP
    name: client
  - port: 6222
    protocol: TCP
    name: cluster
  - port: 8222    
    protocol: TCP
    name: monitor